//! Built-in function bridge for the VM
//!
//! This module provides a bridge between the VM and the runtime's
//! built-in function implementations.

use crate::runtime::builtins;
use crate::runtime::Value;
use std::io::Write;

/// List of all built-in function names (lowercase for case-insensitive matching)
pub const BUILTIN_FUNCTIONS: &[&str] = &[
    // String functions
    "strlen",
    "substr",
    "strtoupper",
    "strtolower",
    "trim",
    "ltrim",
    "rtrim",
    "str_repeat",
    "str_replace",
    "strpos",
    "str_contains",
    "str_starts_with",
    "str_ends_with",
    "ucfirst",
    "lcfirst",
    "ucwords",
    "strrev",
    "str_pad",
    "explode",
    "implode",
    "join",
    "sprintf",
    "chr",
    "ord",
    "htmlspecialchars",
    "htmlentities",
    "nl2br",
    "number_format",
    "md5",
    "sha1",
    "bin2hex",
    "hex2bin",
    "levenshtein",
    "similar_text",
    "strtr",
    // JSON functions
    "json_encode",
    "json_decode",
    // File I/O functions
    "file_get_contents",
    "file_put_contents",
    "file_exists",
    "is_file",
    "is_dir",
    "filemtime",
    "filesize",
    "unlink",
    "is_readable",
    "is_writable",
    // Math functions
    "abs",
    "ceil",
    "floor",
    "round",
    "max",
    "min",
    "pow",
    "sqrt",
    "rand",
    "mt_rand",
    "sin",
    "cos",
    "tan",
    "log10",
    "exp",
    "pi",
    // Type functions
    "intval",
    "floatval",
    "doubleval",
    "strval",
    "boolval",
    "gettype",
    "is_null",
    "is_bool",
    "is_int",
    "is_integer",
    "is_long",
    "is_float",
    "is_double",
    "is_real",
    "is_string",
    "is_array",
    "is_numeric",
    "is_callable",
    "isset",
    "empty",
    "unset",
    "get_class",
    "get_parent_class",
    "get_class_methods",
    "get_class_vars",
    "get_object_vars",
    "method_exists",
    "property_exists",
    "class_exists",
    "interface_exists",
    "trait_exists",
    "is_a",
    "is_subclass_of",
    "get_declared_classes",
    "get_declared_interfaces",
    "get_declared_traits",
    "class_alias",
    "get_defined_functions",
    "func_num_args",
    "func_get_arg",
    "func_get_args",
    // Array functions
    "count",
    "sizeof",
    "array_push",
    "array_pop",
    "array_shift",
    "array_unshift",
    "array_keys",
    "array_values",
    "in_array",
    "array_search",
    "array_reverse",
    "array_merge",
    "array_key_exists",
    "range",
    "array_first",
    "array_last",
    "array_map",
    "array_filter",
    "array_reduce",
    "array_slice",
    "array_sum",
    "array_unique",
    "array_fill",
    "array_fill_keys",
    "array_combine",
    "array_chunk",
    "array_pad",
    "array_splice",
    "array_diff",
    "array_intersect",
    "array_column",
    "array_flip",
    "array_count_values",
    // SPL autoload functions
    "spl_autoload_register",
    "spl_autoload_unregister",
    "spl_autoload_functions",
    "spl_autoload_register_psr4",
    "spl_autoload_registered_psr4",
    "load_psr4_class",
    "set_include_path",
    "get_include_path",
    // File inclusion functions
    "require",
    "require_once",
    // Output functions (handled separately since they need writer)
    "print",
    "var_dump",
    "print_r",
    "printf",
    // Reflection functions (handled in VM)
    "get_class_attributes",
    "get_property_attributes",
    "get_method_attributes",
    "get_method_parameter_attributes",
    "get_function_attributes",
    "get_parameter_attributes",
    "get_interface_attributes",
    "get_trait_attributes",
];

/// Check if a function name is a built-in function
pub fn is_builtin(name: &str) -> bool {
    let lower = name.to_lowercase();
    BUILTIN_FUNCTIONS.contains(&lower.as_str())
}

/// Call a built-in function with the given arguments
/// Returns the result value or an error message
pub fn call_builtin<W: Write>(name: &str, args: &[Value], output: &mut W) -> Result<Value, String> {
    let lower_name = name.to_lowercase();
    match lower_name.as_str() {
        // String functions
        "strlen" => builtins::string::strlen(args),
        "substr" => builtins::string::substr(args),
        "strtoupper" => builtins::string::strtoupper(args),
        "strtolower" => builtins::string::strtolower(args),
        "trim" => builtins::string::trim(args),
        "ltrim" => builtins::string::ltrim(args),
        "rtrim" => builtins::string::rtrim(args),
        "str_repeat" => builtins::string::str_repeat(args),
        "str_replace" => builtins::string::str_replace(args),
        "strpos" => builtins::string::strpos(args),
        "str_contains" => builtins::string::str_contains(args),
        "str_starts_with" => builtins::string::str_starts_with(args),
        "str_ends_with" => builtins::string::str_ends_with(args),
        "ucfirst" => builtins::string::ucfirst(args),
        "lcfirst" => builtins::string::lcfirst(args),
        "ucwords" => builtins::string::ucwords(args),
        "strrev" => builtins::string::strrev(args),
        "str_pad" => builtins::string::str_pad(args),
        "explode" => builtins::string::explode(args),
        "implode" | "join" => builtins::string::implode(args),
        "sprintf" => builtins::string::sprintf(args),
        "chr" => builtins::string::chr(args),
        "ord" => builtins::string::ord(args),
        "htmlspecialchars" => builtins::string_extra::htmlspecialchars(args),
        "htmlentities" => builtins::string_extra::htmlentities(args),
        "nl2br" => builtins::string_extra::nl2br(args),
        "number_format" => builtins::string_extra::number_format(args),
        "md5" => builtins::string_extra::md5(args),
        "sha1" => builtins::string_extra::sha1(args),
        "bin2hex" => builtins::string_extra::bin2hex(args),
        "hex2bin" => builtins::string_extra::hex2bin(args),
        "levenshtein" => builtins::string_extra::levenshtein(args),
        "similar_text" => builtins::string_extra::similar_text(args),
        "strtr" => builtins::string_extra::strtr(args),

        // JSON functions
        "json_encode" => builtins::json_encode(args),
        "json_decode" => builtins::json_decode(args),

        // File I/O functions
        "file_get_contents" => builtins::fileio::file_get_contents(args),
        "file_put_contents" => builtins::fileio::file_put_contents(args, output),
        "file_exists" => builtins::fileio::file_exists(args),
        "is_file" => builtins::fileio::is_file(args),
        "is_dir" => builtins::fileio::is_dir(args),
        "filemtime" => builtins::fileio::filemtime(args),
        "filesize" => builtins::fileio::filesize(args),
        "unlink" => builtins::fileio::unlink(args),
        "is_readable" => builtins::fileio::is_readable(args),
        "is_writable" => builtins::fileio::is_writable(args),

        // Math functions
        "abs" => builtins::math::abs(args),
        "ceil" => builtins::math::ceil(args),
        "floor" => builtins::math::floor(args),
        "round" => builtins::math::round(args),
        "max" => builtins::math::max(args),
        "min" => builtins::math::min(args),
        "pow" => builtins::math::pow(args),
        "sqrt" => builtins::math::sqrt(args),
        "rand" | "mt_rand" => builtins::math::rand(args),
        "sin" => builtins::math::sin(args),
        "cos" => builtins::math::cos(args),
        "tan" => builtins::math::tan(args),
        "log10" => builtins::math::log10(args),
        "exp" => builtins::math::exp(args),
        "pi" => builtins::math::pi(args),

        // Type functions
        "intval" => builtins::types::intval(args),
        "floatval" | "doubleval" => builtins::types::floatval(args),
        "strval" => builtins::types::strval(args),
        "boolval" => builtins::types::boolval(args),
        "gettype" => builtins::types::gettype(args),
        "is_null" => builtins::types::is_null(args),
        "is_bool" => builtins::types::is_bool(args),
        "is_int" | "is_integer" | "is_long" => builtins::types::is_int(args),
        "is_float" | "is_double" | "is_real" => builtins::types::is_float(args),
        "is_string" => builtins::types::is_string(args),
        "is_array" => builtins::types::is_array(args),
        "is_numeric" => builtins::types::is_numeric(args),
        "is_callable" => builtins::types::is_callable(args),
        "isset" => builtins::types::isset(args),
        "empty" => builtins::types::empty(args),
        "unset" => builtins::types::unset(args),
        "get_class" => builtins::type_extra::get_class(args),
        "get_parent_class" => builtins::type_extra::get_parent_class(args),
        "get_class_methods" => builtins::type_extra::get_class_methods(args),
        "get_class_vars" => builtins::type_extra::get_class_vars(args),
        "get_object_vars" => builtins::type_extra::get_object_vars(args),
        "method_exists" => builtins::type_extra::method_exists(args),
        "property_exists" => builtins::type_extra::property_exists(args),
        "class_exists" => builtins::type_extra::class_exists(args),
        "interface_exists" => builtins::type_extra::interface_exists(args),
        "trait_exists" => builtins::type_extra::trait_exists(args),
        "is_a" => builtins::type_extra::is_a(args),
        "is_subclass_of" => builtins::type_extra::is_subclass_of(args),
        "get_declared_classes" => builtins::type_extra::get_declared_classes(args),
        "get_declared_interfaces" => builtins::type_extra::get_declared_interfaces(args),
        "get_declared_traits" => builtins::type_extra::get_declared_traits(args),
        "class_alias" => builtins::type_extra::class_alias(args),
        "get_defined_functions" => builtins::type_extra::get_defined_functions(args),
        "func_num_args" => builtins::type_extra::func_num_args(args),
        "func_get_arg" => builtins::type_extra::func_get_arg(args),
        "func_get_args" => builtins::type_extra::func_get_args(args),

        // Array functions
        "count" | "sizeof" => builtins::array::count(args),
        "array_push" => builtins::array::array_push(args),
        "array_pop" => builtins::array::array_pop(args),
        "array_shift" => builtins::array::array_shift(args),
        "array_unshift" => builtins::array::array_unshift(args),
        "array_keys" => builtins::array::array_keys(args),
        "array_values" => builtins::array::array_values(args),
        "in_array" => builtins::array::in_array(args),
        "array_search" => builtins::array::array_search(args),
        "array_reverse" => builtins::array::array_reverse(args),
        "array_merge" => builtins::array::array_merge(args),
        "array_key_exists" => builtins::array::array_key_exists(args),
        "range" => builtins::array::range(args),
        "array_first" => builtins::array::array_first(args),
        "array_last" => builtins::array::array_last(args),
        "array_map" => builtins::array::array_map(args),
        "array_filter" => builtins::array::array_filter(args),
        "array_reduce" => builtins::array::array_reduce(args),
        "array_slice" => builtins::array::array_slice(args),
        "array_sum" => builtins::array::array_sum(args),
        "array_unique" => builtins::array::array_unique(args),
        "array_fill" => builtins::array_extra::array_fill(args),
        "array_fill_keys" => builtins::array_extra::array_fill_keys(args),
        "array_combine" => builtins::array_extra::array_combine(args),
        "array_chunk" => builtins::array_extra::array_chunk(args),
        "array_pad" => builtins::array_extra::array_pad(args),
        "array_splice" => builtins::array_extra::array_splice(args),
        "array_diff" => builtins::array_extra::array_diff(args),
        "array_intersect" => builtins::array_extra::array_intersect(args),
        "array_column" => builtins::array_extra::array_column(args),
        "array_flip" => builtins::array_extra::array_flip(args),
        "array_count_values" => builtins::array_extra::array_count_values(args),

        // SPL autoload functions
        "spl_autoload_register" => builtins::spl::spl_autoload_register(args),
        "spl_autoload_unregister" => builtins::spl::spl_autoload_unregister(args),
        "spl_autoload_functions" => builtins::spl::spl_autoload_functions(args),
        "spl_autoload_register_psr4" => builtins::spl::spl_autoload_register_psr4(args),
        "spl_autoload_registered_psr4" => builtins::spl::spl_autoload_registered_psr4(args),
        "set_include_path" => builtins::spl::set_include_path(args),
        "get_include_path" => builtins::spl::get_include_path(args),

        // Output functions (need writer)
        "print" => builtins::output::print(output, args),
        "var_dump" => builtins::output::var_dump(output, args),
        "print_r" => builtins::output::print_r(output, args),
        "printf" => builtins::output::printf(output, args),

        _ => Err(format!("Unknown built-in function: {}", name)),
    }
}
